import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import react from "react";
import Info from "../components/info";

export default function Home() {
  return (
    <div className={styles.bg}>
      <div className={styles.container}>
        <Head>
          <title>ok let's go</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <card className={styles.card}>
            <div>
              <h1 className={styles.title}>FIRST STEP</h1>
            </div>
          </card>
          <button onClick={console.log("test")} className={styles.button}>
            press me
          </button>
          <Info></Info>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </div>
  );
}
